#DB選択
USE TEACHERSDB;

DROP TABLE M110_KAIGJKN;
CREATE TABLE M110_KAIGJKN (
	KAIGJKN_CD char(3) NOT NULL,
    HYOJIJN tinyint NOT NULL,
	KAIGJKN_TIME  smallint(3) NOT NULL,
	KAIGJKN_DISP varchar(16) NOT NULL,
	CRTSRV char(5) NOT NULL,
	CRTUSR varchar(30) NOT NULL,
	CRTDATE DATETIME(6) NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR varchar(30) NOT NULL,
	UPDDATE DATETIME(6) NOT NULL,
	DELFLG char(1) NOT NULL,
	PRIMARY KEY(KAIGJKN_CD)
);