#DB選択
USE TEACHERSDB;

DROP TABLE M111_RQYUKJKN;
CREATE TABLE M111_RQYUKJKN (
	YUKJKN_CD char(3) NOT NULL,
    HYOJIJN tinyint NOT NULL,
	YUKJKN_TIME  smallint(3) NOT NULL,
	YUKJKN_DISP varchar(16) NOT NULL,
	CRTSRV char(5) NOT NULL,
	CRTUSR char(18) NOT NULL,
	CRTDATE DATETIME(6) NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR char(18) NOT NULL,
	UPDDATE DATETIME(6) NOT NULL,
	DELFLG char(1) NOT NULL,
	PRIMARY KEY(YUKJKN_CD)
);