#DB選択
USE TEACHERSDB;

DROP TABLE T111_HASHTAG_COUNT;
CREATE TABLE T111_HASHTAG_COUNT (
	#HASHTAG_ID char(18) NOT NULL,
	#HASHTAG_NAIYO varchar(150) ,
	HASHTAG varchar(150) NOT NULL,
    COUNTER_ALL integer default 1,
    COUNTER_Y integer default 1,
    COUNTER_M integer default 1,
    COUNTER_W integer default 1,
    CRTSRV char(5) NOT NULL,
	CRTUSR char(18) NOT NULL,
	CRTDATE DATETIME(6) NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR char(18) NOT NULL,
	UPDDATE DATETIME(6) NOT NULL,
	DELFLG char(1) NOT NULL,
	PRIMARY KEY(HASHTAG)
);