#DB選択
USE TEACHERSDB;

DROP TABLE T120_KAITREQUEST;
CREATE TABLE T120_KAITREQUEST (
	SHITSMN_ID char(18) NOT NULL,
	SEQ  tinyint NOT NULL,
	KAIT_USERID varchar(30) NOT NULL,
    KAIT_USERCOMMENT varchar(512) ,
	REQUESTYUKJKN smallint ,
	REQUESTYUKKGN DATETIME(0) ,
	CRTSRV char(5) NOT NULL,
	CRTUSR char(18) NOT NULL,
	CRTDATE DATETIME(6) NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR char(18) NOT NULL,
	UPDDATE DATETIME(6) NOT NULL,
	DELFLG char(1) NOT NULL,
	PRIMARY KEY(SHITSMN_ID, SEQ, KAIT_USERID)
);
