#DB選択
USE TEACHERSDB;

DROP TABLE T120_KAITREQUEST;
CREATE TABLE T120_KAITREQUEST (
	SHITSMN_ID char(18) NOT NULL,
	SEQ tinyint(2) NOT NULL,
    RQSEQ middleint NOT NULL,
    KAIT_USERID char(18) NOT NULL,
    KAIT_USERCOMMENT varchar(512) ,
    RQYUKJKN smallint(3) ,
    RQYUKKGN DATETIME(6) ,
	CRTSRV char(5) NOT NULL,
	CRTUSR char(18) NOT NULL,
	CRTDATE DATETIME(6) NOT NULL,
	UPDSRV char(5) NOT NULL,
	UPDUSR char(18) NOT NULL,
	UPDDATE DATETIME(6) NOT NULL,
	DELFLG char(1) NOT NULL,
	PRIMARY KEY(SHITSMN_ID,SEQ,RQSEQ)
);